### PR TITLE
run watcher without subprocess

### PR DESCRIPTION
**Pull request by DirtyRacer1337**

### CODE REVIEW

**Comment by Serechops** [comment]
Commit has been reverted. When running app.py, the watcher process takes over the main process, hence why it was moved to a subprocess originally.

**Comment by DirtyRacer1337** [comment]
it doesn't work with poetry

**Comment by DirtyRacer1337** [comment]
make proper solution them I got no idea how it should work, but running python with subprocess not a solution

**Comment by DirtyRacer1337** [comment]
something like that maybe
```py
watcher_thread = threading.Thread(target=watcher_main)
watcher_thread.daemon = True
watcher_thread.start()
```

**Comment by DirtyRacer1337** [comment]
@Serechops you should fix this before release new version

**Pull request merged**
